// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// popmc2
Rcpp::List popmc2(Rcpp::DataFrame df_, Rcpp::NumericVector ymis_index_, Rcpp::List parlist_, Rcpp::Function theta_dens, Rcpp::Function theta_prop, Rcpp::Function d_k_log, Rcpp::Function d_g_log);
RcppExport SEXP _popmcarmatest_popmc2(SEXP df_SEXP, SEXP ymis_index_SEXP, SEXP parlist_SEXP, SEXP theta_densSEXP, SEXP theta_propSEXP, SEXP d_k_logSEXP, SEXP d_g_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df_(df_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ymis_index_(ymis_index_SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parlist_(parlist_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type theta_dens(theta_densSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type theta_prop(theta_propSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type d_k_log(d_k_logSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type d_g_log(d_g_logSEXP);
    rcpp_result_gen = Rcpp::wrap(popmc2(df_, ymis_index_, parlist_, theta_dens, theta_prop, d_k_log, d_g_log));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_popmcarmatest_popmc2", (DL_FUNC) &_popmcarmatest_popmc2, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_popmcarmatest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
