# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

popmc2 <- function(df_, ymis_index_, parlist_, theta_dens, theta_prop, d_k_log, d_g_log) {
    .Call(`_popmcarmatest_popmc2`, df_, ymis_index_, parlist_, theta_dens, theta_prop, d_k_log, d_g_log)
}

